source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'


  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby
  gem 'less-rails'

  gem 'uglifier', '>= 1.0.3'
end

gem "jquery-rails", "~> 2.3.0"

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

# Gems used for handling postgis support
gem 'rgeo'
gem 'rgeo-geojson'
gem 'rgeo-shapefile'
gem 'activerecord-postgis-adapter'

# Gem to provide our postgis clustering extensions
gem 'rp_clustering-rgeo-activerecord' #, :path => "~/Documents/Git/rp_clustering-rgeo-activerecord"

# Gems used for handling lower level SQL queries
gem 'squeel'

# Gems used for authentication
gem 'devise'

# Gems providing additional generators
gem 'nested_scaffold'

# Annotate model's with schema information
gem 'annotate', ">=2.5.0"

# Gem for authentication
gem "devise"
gem 'devise_cas_authenticatable'
