// Generated by CoffeeScript 1.3.3

/*
# Code to control the classify a habitat interface
*/


(function() {

  Edgar.vetting.classifyHabitat = {
    /*
        # Init the classify Habitat
        #
        # This is run once
    */

    init: function() {
      var classifyHabitat;
      consolelog("Starting to init the classify habitat interface");
      classifyHabitat = Edgar.vetting.classifyHabitat;
      classifyHabitat.wkt = new OpenLayers.Format.WKT({
        'internalProjection': Edgar.map.baseLayer.projection,
        'externalProjection': Edgar.util.projections.mercator
      });
      consolelog("Finished init-ing the classify habitat interface");
      null;
      classifyHabitat.vectorLayerOptions = {
        /*
                    # NOTE: Due to OpenLayers Bug.. can't do this.
                    #   The modify feature control draws points onto the vector layer
                    #   to show vertice drag points.. these drag points fail the geometryType
                    #   test.
                    # 'geometryType': OpenLayers.Geometry.Polygon
        */

      };
      classifyHabitat._addButtonHandlers();
      consolelog("Finished init new vetting");
      return null;
    },
    /*
        # Code to add button click even handlers to DOM
    */

    _addButtonHandlers: function() {
      /*
              handle draw polygon press
      */

      var vetform, vetpanel;
      $('#newvet_draw_polygon_button').click(function(e) {
        _handleDrawPolygonClick(e);
        return null;
      });
      /*
              handle add polygon press
      */

      $('#newvet_add_polygon_button').click(function(e) {
        _handleAddPolygonClick(e);
        return null;
      });
      /*
              handle modify polygon press
      */

      $('#newvet_modify_polygon_button').click(function(e) {
        _handleModifyPolygonClick(e);
        return null;
      });
      /*
              handle delete selected polygon press
      */

      $('#newvet_delete_selected_polygon_button').click(function(e) {
        _handleDeleteSelectedPolygonClick(e);
        return null;
      });
      /*
              handle delete all polygon press
      */

      $('#newvet_delete_all_polygons_button').click(function(e) {
        _handleDeleteAllPolygonClick(e);
        return null;
      });
      /*
              toggle the ui-state-hover class on hover events
      */

      $('#newvet :button').hover(function() {
        var classifyHabitat;
        classifyHabitat = Edgar.vetting.classifyHabitat;
        $(classifyHabitat).addClass("ui-state-hover");
        return null;
      }, function() {
        var classifyHabitat;
        classifyHabitat = Edgar.vetting.classifyHabitat;
        $(classifyHabitat).removeClass("ui-state-hover");
        return null;
      });
      /*
              listen for newvet form submission
      */

      vetpanel = $('#newvet');
      vetform = $('#vetform');
      return $('#vet_submit').click(function(e) {
        e.preventDefault();
        /*
                    # validate the form
                    # and, if valid, submit its contents
        */

        if (_validateNewVetForm()) {
          return _createNewVetting();
        } else {
          return false;
        }
      });
    },
    engage: function() {
      consolelog("Starting engageClassifyHabitatInterface");
      _addVectorLayer();
      _addDrawControl();
      _addModifyControl();
      consolelog("Finished engageClassifyHabitatInterface");
      return null;
    },
    _addVectorLayer: function() {
      var classifyHabitat;
      classifyHabitat = Edgar.vetting.classifyHabitat;
      /*
              # Define a vector layer to hold a user's area classification
      */

      classifyHabitat.vectorLayer = new OpenLayers.Layer.Vector("New Area Classification", classifyHabitat.vectorLayerOptions);
      return Edgar.map.addLayers([classifyHabitat.vectorLayer]);
    },
    _removeVectorLayer: function() {
      return null;
    },
    _addDrawControl: function() {
      var classifyHabitat;
      classifyHabitat = Edgar.vetting.classifyHabitat;
      classifyHabitat.drawControl = new OpenLayers.Control.DrawFeature(classifyHabitat.vectorLayer, OpenLayers.Handler.Polygon);
      Edgar.map.addControl(classifyHabitat.drawControl);
      return null;
    },
    _removeDrawControl: function() {
      return null;
    },
    _addModifyControl: function() {
      var classifyHabitat;
      classifyHabitat = Edgar.vetting.classifyHabitat;
      /*
              # Create a Modify Feature control
              # Allow users to:
              #    - Reshape
              #    - Drag
      */

      classifyHabitat.modifyControl = new OpenLayers.Control.ModifyFeature(classifyHabitat.vectorLayer, {
        mode: OpenLayers.Control.ModifyFeature.RESHAPE | OpenLayers.Control.ModifyFeature.DRAG,
        beforeSelectFeature: function(feature) {
          $('#newvet_delete_selected_polygon_button').attr("disabled", false).removeClass("ui-state-disabled");
          return null;
        },
        unselectFeature: function(feature) {
          $('#newvet_delete_selected_polygon_button').attr("disabled", true).addClass("ui-state-disabled");
          return null;
        }
      });
      return null;
    },
    _removeModifyControl: function() {
      return null;
    },
    _clearNewVettingMode: function(e) {
      var classifyHabitat;
      classifyHabitat = Edgar.vetting.classifyHabitat;
      consolelog("Clearing classify habitat mode of operation");
      removeModifyFeatureHandlesAndVertices();
      classifyHabitat.drawControl.deactivate();
      $('#newvet_draw_polygon_button').removeClass('ui-state-active');
      classifyHabitat.modifyControl.deactivate();
      $('#newvet_modify_polygon_button').removeClass('ui-state-active');
      _updateNewVetHint();
      return null;
    },
    _activateDrawPolygonMode: function() {
      _clearNewVettingMode();
      $('#newvet_draw_polygon_button').addClass('ui-state-active');
      new_vet_draw_polygon_control.activate();
      _updateNewVetHint();
      return null;
    },
    _activateModifyPolygonMode: function() {
      _clearNewVettingMode();
      $('#newvet_modify_polygon_button').addClass('ui-state-active');
      classifyHabitat.modifyControl.mode = OpenLayers.Control.ModifyFeature.RESHAPE | OpenLayers.Control.ModifyFeature.DRAG;
      classifyHabitat.modifyControl.activate();
      return _updateNewVetHint();
    },
    _handleToggleButtonClick: function(e, onActivatingButton, onDeactivatingButton) {
      e.preventDefault();
      if ($(e.srcElement).hasClass('ui-state-active')) {
        onDeactivatingButton();
      } else {
        onActivatingButton();
      }
      return null;
    },
    _handleDrawPolygonClick: function(e) {
      _handleToggleButtonClick(e, _activateDrawPolygonMode, _clearNewVettingMode);
      return null;
    },
    _handleModifyPolygonClick: function(e) {
      _handleToggleButtonClick(e, _activateModifyPolygonMode, _clearNewVettingMode);
      return null;
    },
    _handleAddPolygonClick: function(e) {
      var attributes, calcDimension, centerOfMap, classifyHabitat, feature, majorFraction, mapBounds, mapHeight, mapWidth, minorFraction, points, polygon, ring;
      classifyHabitat = Edgar.vetting.classifyHabitat;
      e.preventDefault();
      _clearNewVettingMode();
      centerOfMap = Edgar.map.getCenter;
      mapBounds = Edgar.map.getExtent;
      mapHeight = mapBounds.top - mapBounds.bottom;
      mapWidth = mapBounds.right - mapBounds.left;
      calcDimension = null;
      if (mapHeight > mapWidth) {
        calcDimension = mapHeight;
      } else {
        calcDimension = mapWidth;
      }
      majorFraction = calcDimension / 10;
      minorFraction = calcDimension / 14;
      points = [new OpenLayers.Geometry.Point(centerOfMap.lon - minorFraction, centerOfMap.lat - majorFraction), new OpenLayers.Geometry.Point(centerOfMap.lon - majorFraction, centerOfMap.lat), new OpenLayers.Geometry.Point(centerOfMap.lon, centerOfMap.lat + minorFraction), new OpenLayers.Geometry.Point(centerOfMap.lon + majorFraction, centerOfMap.lat), new OpenLayers.Geometry.Point(centerOfMap.lon + minorFraction, centerOfMap.lat - majorFraction)];
      ring = new OpenLayers.Geometry.LinearRing(points);
      polygon = new OpenLayers.Geometry.Polygon([ring]);
      attributes = {};
      feature = new OpenLayers.Feature.Vector(polygon, attributes);
      classifyHabitat.vectorLayer.addFeatures([feature]);
      _activateModifyPolygonMode();
      return null;
    },
    _removeModifyFeatureHandlesAndVertices: function() {
      var classifyHabitat;
      classifyHabitat = Edgar.vetting.classifyHabitat;
      classifyHabitat.vectorLayer.addFeatures([feature]);
      classifyHabitat.vectorLayer.removeFeatures(classifyHabitat.modifyControl.virtualVertices, {
        silent: true
      });
      classifyHabitat.vectorLayer.removeFeatures(classifyHabitat.modifyControl.vertices, {
        silent: true
      });
      classifyHabitat.vectorLayer.removeFeatures(classifyHabitat.modifyControl.radiusHandle, {
        silent: true
      });
      classifyHabitat.vectorLayer.removeFeatures(classifyHabitat.modifyControl.dragHandle, {
        silent: true
      });
      return null;
    },
    _handleDeleteSelectedPolygonClick: function(e) {
      var classifyHabitat, currentFeature;
      e.preventDefault();
      classifyHabitat = Edgar.vetting.classifyHabitat;
      currentFeature = classifyHabitat.modifyControl.feature;
      if (currentFeature) {
        classifyHabitat.modifyControl.unselectFeature(currentFeature);
        _removeModifyFeatureHandlesAndVertices();
        classifyHabitat.vectorLayer.removeFeatures(currentFeature);
        if (classifyHabitat.vectorLayer.features.length === 0) {
          _clearNewVettingMode();
        }
      }
      return null;
    },
    _handleDeleteAllPolygonClick: function(e) {
      var classifyHabitat;
      e.preventDefault();
      classifyHabitat = Edgar.vetting.classifyHabitat;
      _clearNewVettingMode();
      classifyHabitat.vectorLayer.removeAllFeatures();
      _updateNewVetHint();
      return null;
    },
    _updateNewVetHint: function() {
      var drawPolygonHints, hint, modifyPolygonHints, movePolygonHints;
      drawPolygonHints = [''];
      modifyPolygonHints = ['<p>Press <strong>Delete</strong> while over a corner to delete it</p>'];
      movePolygonHints = [''];
      if (new_vet_modify_polygon_control.active) {
        hint = modifyPolygonHints[Math.floor(Math.random() * modifyPolygonHints.length)];
        $('#vethint').html(hint);
      } else if (new_vet_draw_polygon_control) {
        hint = drawPolygonHints[Math.floor(Math.random() * drawPolygonHints.length)];
        $('#vethint').html(hint);
      } else {
        $('#vethint').html('');
      }
      return null;
    },
    _createNewVetting: function() {
      var classifyHabitat, feature, layerWKTString, newVetData, newVetPolygon, newVetPolygonFeatures, newVetPolygonGeoms, speciesId, url, vetDataAsJSONString, _i, _len;
      consolelog("Processing create new vetting");
      classifyHabitat = Edgar.vetting.classifyHabitat;
      newVetPolygonFeatures = classifyHabitat.features;
      newVetPolygonGeoms = [];
      for (_i = 0, _len = newVetPolygonFeatures.length; _i < _len; _i++) {
        feature = newVetPolygonFeatures[_i];
        newVetPolygonGeoms.push(feature.geometry);
      }
      newVetPolygon = new OpenLayers.Geometry.MultiPolygon(newVetPolygonGeoms);
      consolelog("WKT logs:");
      consolelog("polygon", newVetPolygon);
      layerWKTString = classifyHabitat.wkt.extractGeometry(newVetPolygon);
      consolelog("layer string", layerWKTString);
      speciesId = Edgar.mapdata.species.id;
      newVetData = {
        area: layerWKTString,
        species_id: speciesId,
        comment: $("#vetcomment").val(),
        classification: $("#vetclassification").val()
      };
      consolelog("Post Data", newVetData);
      vetDataAsJSONString = JSON.stringify(newVetData);
      consolelog("Post Data as JSON", vetDataAsJSONString);
      url = Edgar.baseUrl + "species/insert_vetting/" + species_id + ".json";
      $.post(url, vet_data_as_json_str, function(data, text_status, jqXHR) {
        consolelog("New Vet Response", data, text_status, jqXHR);
        return alert("New Vet Response: " + data);
      }, 'json');
      return true;
    },
    _validateNewVetForm: function() {
      var classifyHabitat, newVetPolygonFeatures;
      classifyHabitat = Edgar.vetting.classifyHabitat;
      newVetPolygonFeatures = classifyHabitat.features;
      if (Edgar.mapdata.species === null) {
        alert("No species selected");
        return false;
      } else if (new_vet_polygon_features.length === 0) {
        alert("No polygons provided");
        $('#newvet_add_polygon_button').effect("highlight", {}, 5000);
        return false;
      } else if ($('#vetclassification').val() === '') {
        alert("No classification provided");
        $('#vetclassification').effect("highlight", {}, 5000);
        return false;
      } else {
        return true;
      }
    }
  };

}).call(this);
