// Generated by CoffeeScript 1.3.3

/*
# Code to control the classify a habitat interface
*/


(function() {

  Edgar.vetting.myHabitatClassifications = {
    /*
        # Init the my habitat classifications
        #
        # This is run once
    */

    init: function() {
      consolelog("Starting to init the my habitat classifications interface");
      consolelog("Finished init-ing the classify habitat interface");
      return null;
    },
    _addVectorLayer: function() {
      this.vectorLayer = new OpenLayers.Layer.Vector('My Habitat Classifications', {
        isBaseLayer: false,
        projection: Edgar.util.projections.geographic,
        strategies: [
          new OpenLayers.Strategy.BBOX({
            resFactor: 1.1
          })
        ],
        protocol: new OpenLayers.Protocol.HTTP({
          url: Edgar.baseUrl + "species/vetting_geo_json/" + Edgar.mapdata.species.id + ".json",
          format: new OpenLayers.Format.GeoJSON({}),
          params: {
            by_user_id: Edgar.user.id
          }
        }),
        styleMap: Edgar.vetting.areaStyleMap
      });
      return Edgar.map.addLayer(this.vectorLayer);
    },
    _removeVectorLayer: function() {
      Edgar.map.removeLayer(this.vectorLayer);
      delete this.vectorLayer;
      return null;
    },
    engage: function() {
      consolelog("Starting engageMyHabitatClassifications");
      this._addVectorLayer();
      consolelog("Finished engageMyHabitatClassifications");
      return null;
    },
    disengage: function() {
      consolelog("Starting disengageMyHabitatClassifications");
      this._removeVectorLayer();
      return consolelog("Finished disengageMyHabitatClassifications");
    },
    isChangeModeOkay: function(newMode) {
      return true;
    }
  };

}).call(this);
