// Generated by CoffeeScript 1.3.3

/*
File to control entering and exiting vetting modes.
*/


(function() {

  Edgar.vetting = {};

  /*
  get ready to do vetting.  gets called by mapmodes.js, after
  the vetting tools have been switched on
  */


  Edgar.vetting.engageVettingMode = function() {
    console.log("engageVettingMode");
    return null;
  };

  /*
  wrap up the vetting mode.  gets called by mapmodes.js, before
  the vetting tools have been hidden
  */


  Edgar.vetting.disengageVettingMode = function() {
    console.log("disengageVettingMode");
    return null;
  };

}).call(this);
