// Generated by CoffeeScript 1.3.3

/*
# File to control entering and exiting vetting modes.
*/


(function() {

  Edgar.vetting = {
    /*
        # Initialise the classify habitat interface
    */

    init: function() {
      Edgar.vetting.classifyHabitat.init();
      this._bindToChangeModeEvents();
      return null;
    },
    /*
        # Bind to the change mode events that occurr on the map
    */

    _bindToChangeModeEvents: function() {
      return $(Edgar.map).on('changemode', function(event, newMode) {
        if (!Edgar.vetting.isChangeModeOkay(newMode)) {
          return event.preventDefault();
        }
      });
    },
    isChangeModeOkay: function(newMode) {
      if (Edgar.mapmode === 'vetting') {
        if (this.classifyHabitat.isChangeModeOkay(newMode)) {
          return true;
        } else {
          consolelog('cancelling mode change.');
          return false;
        }
      } else {
        return true;
      }
    },
    /*
        # get ready to do vetting.  gets called by mapmodes.js, after
        # the vetting tools have been switched on
    */

    engageVettingMode: function() {
      console.log("engageVettingMode");
      Edgar.vetting.classifyHabitat.engage();
      return null;
    },
    /*
        # wrap up the vetting mode.  gets called by mapmodes.js, before
        # the vetting tools have been hidden
    */

    disengageVettingMode: function() {
      console.log("disengageVettingMode");
      Edgar.vetting.classifyHabitat.disengage();
      return null;
    }
  };

  /*
  # Document Ready..
  */


  $(function() {
    return Edgar.vetting.init();
  });

}).call(this);
