// Generated by CoffeeScript 1.3.3

/*
initialise some global variables and whatnot
*/


/*
the global Edgar object
*/


(function() {

  window.Edgar = window.Edgar || {};

  /*
  the species map itself
  */


  Edgar.map = Edgar.map || null;

  /*
  mode: one of 'blank', 'current', 'future', 'vetting'
  don't set this directly, use:    $(Edgar.map).trigger('changemode','future'); // to change into future mode, for example
  */


  Edgar.mapmode = Edgar.mapmode || 'blank';

  /*
  vars related to the species map
  */


  Edgar.mapdata = Edgar.mapdata || {};

  Edgar.mapdata.species = null;

  Edgar.mapdata.emissionScenario = null;

  Edgar.mapdata.year = null;

  Edgar.mapdata.layers = {};

  Edgar.mapdata.layers.currentsuitability = null;

  Edgar.mapdata.layers.occurrences = null;

  Edgar.mapdata.layers.selectoccurrencecontrol = null;

  Edgar.mapdata.controls = {};

  Edgar.mapdata.controls.occurrencesSelectControl = null;

  /*
  logged in user?  This is set in fullscreencontent.ctp if there's a logged in user
  */


  Edgar.user = Edgar.user || null;

  Edgar.util = Edgar.util || {};

  /*
  humanise where possible
  */


  Edgar.util.pluralise = function(count, noun, plural) {
    if (count === 1) {
      return count + " " + noun;
    } else if (plural) {
      return count + " " + plural;
    } else {
      return count + " " + noun + "s";
    }
  };

  Edgar.util.showhide = function(showlist, hidelist) {
    $.each(hidelist, function(i, itemid) {
      var $item;
      $item = $('#' + itemid);
      if ($item.css('display') !== 'none') {
        return $item.hide('blind', 'fast');
      }
    });
    return $.each(showlist, function(i, itemid) {
      var $item;
      $item = $('#' + itemid);
      return $item.show('blind', 'fast');
    });
  };

  Edgar.util.mappath = function(species, year, scenario) {
    var speciesid;
    speciesid = species;
    if (typeof species === 'object') {
      speciesid = species.id;
    }
    if (typeof year === 'string' && year.toLowerCase() === 'current') {
      return "" + speciesid + "/1990.asc";
    } else {
      return "" + speciesid + "/" + scenario + "_median_" + year + ".asc";
    }
  };

}).call(this);
