// Generated by CoffeeScript 1.3.3

/*
initialise some global variables and whatnot
*/


/*
the global Edgar object
*/


(function() {

  window.Edgar = window.Edgar || {};

  /*
  the species map itself
  */


  Edgar.map = Edgar.map || null;

  /*
  mode: one of 'blank', 'current', 'future', 'vetting'
  don't set this directly, use:    $(Edgar.map).trigger('changemode','future'); // to change into future mode, for example
  */


  Edgar.mapmode = Edgar.mapmode || 'blank';

  /*
  vars related to the species map
  */


  Edgar.mapdata = Edgar.mapdata || {};

  Edgar.mapdata.species = null;

  Edgar.mapdata.emissionScenario = null;

  Edgar.mapdata.year = null;

  /*
  logged in user?  This is set in fullscreencontent.ctp if there's a logged in user
  */


  Edgar.user = Edgar.user || null;

}).call(this);
