defaults: &defaults
  adapter: postgis
  encoding: unicode
  username: edgar_on_rails
  password: password
  pool: 5
  host: localhost
  port: 5432

  # Should point to your postgis scripts folder
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5/

development:
  <<: *defaults
  database: edgar_on_rails_dev_db

test:
  <<: *defaults
  database: edgar_on_rails_test_db

production:
  <<: *defaults
  database: edgar_on_rails_prod_db
