defaults: &defaults
  adapter: postgis
  encoding: unicode
  username: edgar_on_rails
  password: password
  pool: 5
  host: 127.0.0.1
  port: 5432

  # PostGIS 1.5: Should point to your postgis scripts folder
  # script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5/
  
  # PostGIS 2:
  postgis_extension: postgis
  schema_search_path: public, postgis

development:
  <<: *defaults
  database: edgar_on_rails_dev_db

test:
  <<: *defaults
  database: edgar_on_rails_test_db

production:
  <<: *defaults
  database: edgar_on_rails_prod_db
