defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: edgar_user
  password: edgar_password
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *defaults
  database: edgar_dev

test:
  <<: *defaults
  database: edgar_test

production:
  <<: *defaults
  database: edgar
